### ISSUE TITLE
Build GRCh38 chromosome names

### ISSUE THREAD

**Issue by fa8sanger** [ToolsVanBox/PTATO#21]
Dear colleagues, I am setting things up and was wondering if the pipeline would work with hg38 with "chr" prefixes in the chromosome names. That's the version we have installed but I noticed the PTATO resources for hg38 show no "chr" prefix. Should I obtain a version of hg38 without "chr"?
Thank you!
Federico

**Comment by rhagelaar** [comment]
Dear Federico, 

It is possible to run PTATO with prefix "chr". The trick is to adjust all the other resources with the same prefix. We currently have everything set up without a prefix. But I have run PTATO with prefix in the past as well. 

Hope this helps, 
Rico

**Comment by fa8sanger** [comment]
Thank you, Rico. That's helpful to know!
Would it be too difficult to prepare all the resources for GRCh37? At some point we may need to go that route

**Comment by rhagelaar** [comment]
In general it is similar to set up all the resources for GRCh37 as for GRCh38. It is a matter of matching all files/resources from a different genome-build

**Comment by fa8sanger** [comment]
Thank you, Rico, I see. I'll close this but in case you ever have a shareable GRCh37 version of the resources please let us know. 
Fede

**Comment by rhagelaar** [comment]
Hi Federico, 

I discussed this internally, and it is possible to run on GRCh37. However there is a caveat. The random forrest, which flags and removes the PTA artefacts, is trained on hg38 positions. So besides all the resources, if you want to run PTATO on GRCh37, the random forrest needs to be retrained and you would need sufficient samples for that (more than 1500 mutations per input-group and the more the better).

So I don't know how feasible it is for you. Hope this clarifies things, 
Rico

**Comment by fa8sanger** [comment]
Thank you, Rico, that's very helpful, we'll rely on liftover to compare GRCh38 vs GRCh37, no problem
Fede
