### ISSUE TITLE
Issue submitting slurm jobs to HPC

### ISSUE THREAD

**Issue by ssschulz** [ToolsVanBox/PTATO#4]
Hello, I've been getting the following error while trying to run this package:

```
Error executing process > 'get_gzipped_vcfs:bgzip (bgzip test)'

Caused by:
  Failed to submit process to grid scheduler for execution

Command executed:

  sbatch .command.run

Command exit status:
  1

Command output:
  sbatch: error: Batch job submission failed: Invalid feature specification

```

I think this might be being caused by the following line in the .command.run file: 

`#SBATCH --constraint=avx2`

Do you know if it's necessary to run this line through slurm or if I can change it somewhere? Is this the source of the error or could something else be giving a batch job submission failure here?

**Comment by mroosmalen** [comment]
Hi

avx2 is needed for shapeit. In our cluster not all the nodes has avx2 available, so we need to add a constraint to the nodes which has avx2 available. If all of your nodes in the cluster have avx2 available you can try to remove this line from the nextflow.config.

See this issue about the avx2 and shapeit:
https://github.com/odelaneau/shapeit4/issues/28#issuecomment-1430336761
