### ISSUE TITLE
Issue running smurf

### ISSUE THREAD

**Issue by jeanq1** [ToolsVanBox/PTATO#5]
Hi, I am getting the following error from the pipeline, related to Smurf, 
I have been trying to fix it over the last few days, do you know what might be wrong ?

Error: 

Error executing process > 'short_variants:get_somatic_vcfs:smurf (SMuRF myfile.vcf)'

Caused by:
  Process `short_variants:get_somatic_vcfs:smurf (SMuRF myfile.vcf)` terminated with an error exit status (1)

Command executed:

  host=$(hostname)
  echo ${host}
  
  export projectDir=/apps/PTATO
  
  python /smurf/SMuRF.py     -i myfile.vcf.gz      -b /work/fe/9dd25d0001393ff0faac5afcdaa6c6/Invitro_H1.bam -b /work/80/5c3c1bcabad477d1367007327d3c86/Invitro_Bulk.bam      -n Invitro_Bulk     -t 8     -c /apps/PTATO/resources/hg38/smurf/config_15cov.ini
  
  bash /smurf/scripts/split_in_single_sample_vcfs.sh myfile.8X.SMuRF.filtered.vcf
  
  for BULK in  -n Invitro_Bulk; do
    if [[ "${BULK}" != "-n" ]]; then
      rm myfile_${BULK}.SMuRF.filtered.vcf*
    fi
  done

Command exit status:
  1

Command error:
  Config file /apps/PTATO/resources/hg38/smurf/config_15cov.ini does not exists
  grep: myfile.SMuRF.filtered.vcf: No such file or directory
  grep: myfile.SMuRF.filtered.vcf: No such file or directory
  grep: myfile.SMuRF.filtered.vcf: No such file or directory
  grep: myfile.SMuRF.filtered.vcf: No such file or directory

  rm: cannot remove ‘myfile_Invitro_Bulk.SMuRF.filtered.vcf*’: No such file or directory

Work dir:
 	/work/c7/5146411a97053bcf075d359fff81be

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

Thanks!

**Comment by mroosmalen** [comment]
Can you please check if this (config) file exists.

/apps/PTATO/resources/hg38/smurf/config_15cov.ini

**Comment by jeanq1** [comment]
Hi ! 
Yes it does exist, this is why this issue is quite unsettling

**Comment by mroosmalen** [comment]
I have been able to "recreate" your error. Could it be that you didn't bind the path to your singularity? Can you change this line in the nextflow.config

```
  runOptions = '-B /hpc -B $TMPDIR:$TMPDIR'
  ```
  to
```
  runOptions = '-B /apps -B $TMPDIR:$TMPDIR'
 ```

Maybe also good the check which (version of) singularity you use. We currently working on making a docker file and we had also some problems with singularity in the docker. When we changed it to `apptainer version 1.1.3-1.el8` it looks like it works.

**Comment by jeanq1** [comment]
Thank you very much ! It solved my issue with singularity
