### ISSUE TITLE
Issue executing process short_variants:get_ab_tables:shapeit,  ERROR: No variants to be phased in files

### ISSUE THREAD

**Issue by ssschulz** [ToolsVanBox/PTATO#7]
Hello,

I ran into the following error attempting to run PTATO ` ERROR: No variants to be phased in files` while running shapeit 4, more detailed logs are attached. I was wondering if it had anything to do with this issue: odelaneau/shapeit4#33 

If it is caused by the --region argument in shapeit4, is there a convenient way to either run with --region chr# or change the vcf file to use different chr region numebrs? Do I need to reformat my vcf file in some way?

More detailed logs:
[slurm-14735430.out.txt](https://github.com/ToolsVanBox/PTATO/files/11143082/slurm-14735430.out.txt)
[command.run.txt](https://github.com/ToolsVanBox/PTATO/files/11143083/command.run.txt)

Head of vcf file I used:
[head_vcf.txt](https://github.com/ToolsVanBox/PTATO/files/11143099/head_vcf.txt)

**Comment by mroosmalen** [comment]
Hi

The problem look like it is the chromosome prefix. I assume that the chromosomes in your data have the "chr" prefix. By default the shapeit files has also the "chr" prefix. In our data we deleted the "chr" prefix and did this also in the downloaded shapeit files. 

What you also can try for now, is change this line (line 21) in the following file:
https://github.com/ToolsVanBox/PTATO/blob/main/NextflowModules/shapeit/4.2.2/shapeit.nf

```
    --region ${chrom} \
```
 to 
```
    --region chr${chrom} \
```

In the next release we try to make it more flexible.

**Comment by ssschulz** [comment]
This worked to generate ab tables!
