### ISSUE TITLE
SMuRF missing output

### ISSUE THREAD

**Issue by shngk** [ToolsVanBox/PTATO#9]
Hello, 

Would it be possible to get an example of the final PTATO output, particularly regarding the SMuRF part of the pipeline?

When I run PTATO, it completes successfully according to the NextFlow report, but in the SMuRF folder the vcfs show no variants. In the output folder, there are only two folders, intermediate and log, so I'm not sure whether there are supposed to be more files. 
[Nextflow Workflow Report.pdf](https://github.com/ToolsVanBox/PTATO/files/11288626/Nextflow.Workflow.Report.pdf)

Just to check the SMuRF part of the pipeline, I tried to pass a vcf containing only a single variant that we checked would pass all of the SMuRF filters through PTATO, but it seems the pipeline needs germline variants to run. Could you verify that this variant contained in the file should end up in the SmuRF.filtered.vcf file? 

`#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	Invitro_Bulk	Invitro_H1
1       207128644       .       T       G       117.91  .       AC=1;AF=0.250;AN=4;BaseQRankSum=-1.320e+00;DP=43;ExcessHet=0.0000;FS=0.000;MLEAC=1;MLEAF=0.250;MQ=60.00;MQRankSum=0.00;QD=9.83;ReadPosRankSum=1.88;SOR=0.883       GT:AD:DP:GQ:PL     0/0:30,0:30:84:0,84,1260        0/1:7,5:12:99:126,0,203`

Thanks!

**Comment by mroosmalen** [comment]
We are working on a demo dataset, which can be found here:

https://surfdrive.surf.nl/files/index.php/s/l3FX6eLnTtuVK1g

Can you have a look please, and let me know if this helps you?

**Comment by shngk** [comment]
This is helpful, and gives me a good idea of what the output files should look like. I don't think I am getting the full output because there are only 2 folders in output, `intermediate` and `log`. 

When I try to run the ptato pipeline using the demo dataset, I keep getting this error:


`Error executing process > 'short_variants:get_ab_tables:shapeit (shapeit donor1 21)'

Caused by:
  Process `short_variants:get_ab_tables:shapeit (shapeit donor1 21)` terminated with an error exit status (1)

Command executed:

  host=$(hostname)
  echo ${host}
  
  shapeit4     --input demo.chr20.germline.vcf.gz     --region 21     --output demo.chr20.21.phased.vcf.gz     --map /gpfs/commons/groups/landau_lab/tprieto/apps/PTATO/resources/hg38/shapeit/shapeit_maps/chr21.b38.gmap.gz     --thread 8     --sequencing     --reference /gpfs/commons/groups/landau_lab/tprieto/apps/PTATO/resources/hg38/shapeit/Phasing_reference/CCDG_14151_B01_GRM_WGS_2020-08-05_chr21.filtered.shapeit2-duohmm-phased.vcf.gz

Command exit status:
  1

Command output:
  pe2cc3-034.c.nygenome.org
  
  SHAPEIT
    * Author        : Olivier DELANEAU, University of Lausanne
    * Contact       : olivier.delaneau@gmail.com
    * Version       : 4.2.2
    * Run date      : 21/04/2023 - 15:51:18
  
  Files:
    * Input VCF     : [demo.chr20.germline.vcf.gz]
    * Reference VCF : [/gpfs/commons/groups/landau_lab/tprieto/apps/PTATO/resources/hg38/shapeit/Phasing_reference/CCDG_14151_B01_GRM_WGS_2020-08-05_chr21.filtered.shapeit2-duohmm-phased.vcf.gz]
    * Genetic Map   : [/gpfs/commons/groups/landau_lab/tprieto/apps/PTATO/resources/hg38/shapeit/shapeit_maps/chr21.b38.gmap.gz]
    * Output VCF    : [demo.chr20.21.phased.vcf.gz]
  
  Parameters:
    * Seed    : 15052011
    * Threads : 8 threads
    * MCMC    : 15 iterations [5b + 1p + 1b + 1p + 1b + 1p + 5m]
    * PBWT    : Depth of PBWT neighbours to condition on: 4
    * PBWT    : Store indexes at variants [MAC>=2 / MDR<=0.5 / Dist=0.0004 cM]
    * HMM     : K is variable / min W is 2.50cM / Ne is 15000
    * HMM     : Recombination rates given by genetic map
    * HMM     : AVX2 optimization active
  
  Initialization:
    * VCF/BCF scanning ...
  ERROR: No variants to be phased in files`
[Nextflow Workflow Report Demo.pdf](https://github.com/ToolsVanBox/PTATO/files/11298884/Nextflow.Workflow.Report.Demo.pdf)

**Comment by um-pdavila** [comment]
> We are working on a demo dataset, which can be found here:
> 
> https://surfdrive.surf.nl/files/index.php/s/l3FX6eLnTtuVK1g
> 
> Can you have a look please, and let me know if this helps you?

Thank you for sharing this.  Can you please post the run.config used to generate these results or confirm the following is correct?

$ cat configs/run.config
...
  // TESTING
  input_vcfs_dir = "${projectDir}/input/vcf"
  bams_dir = "${projectDir}/input/bams"
  // END TESTING

  out_dir = ''
  bulk_names = [
    ['donor1', 'donor1'],
  ]
  ...

**Comment by mroosmalen** [comment]
There should be more in the in the output dir (what I can see). I have added also the the run config file to the link. Please use this link and point to the right resources.config (in the demo resources folder)

**Comment by mroosmalen** [comment]
The demo data contains only chromosome 20. The error that you get is that it can't phase variants on chromosome 21 (--region 21), what makes sense because the demo set only contains variants on chromosome 20. I assume that your chromosomes.txt (`"/gpfs/commons/groups/landau_lab/tprieto/apps/PTATO/resources/hg38/shapeit/chromosomes.txt"`) files contains every chromosome. Can you try it with the chromosomes.txt file from the demo data, this file should only contain chromosome 20.

**Comment by shngk** [comment]
Trying the chromosomes.txt from the demo data solves that error, now I get this error: 

```
  Tue Apr 25 11:17:28 EDT 2023: Running GRIDSS steps: setupreference, preprocess, assemble, call,
  Tue Apr 25 11:17:28 EDT 2023: Start pre-processing	PMCAHH1-WT-C6_dedup.chr20.bam
  Tue Apr 25 11:17:28 EDT 2023: Running	CollectGridssMetrics	PMCAHH1-WT-C6_dedup.chr20.bam	first 10000000 records
  "$timecmd java -Xmx$otherjvmheap $jvm_args -cp $gridss_jar gridss.analysis.CollectGridssMetrics REFERENCE_SEQUENCE=$reference TMP_DIR=$dir ASSUME_SORTED=true I=$f O=$tmp_prefix THRESHOLD_COVERAGE=$maxcoverage FILE_EXTENSION=null GRIDSS_PROGRAM=null GRIDSS_PROGRAM=CollectIdsvMetrics PROGRAM=null PROGRAM=CollectInsertSizeMetrics STOP_AFTER=$metricsrecords $picardoptions" command completed with exit code 1.
```

`ERROR   2023-04-25 15:17:34     ReferenceCommandLineProgram     Reference genome used by PMCAHH1-WT-C6_dedup.chr20.bam does not match reference genome /gpfs/commons/groups/landau_lab/tprieto/apps/PTATO/resources/hg38/Homo_sapiens_assembly38.fasta. The reference supplied must match the reference used for every input.`

However, I think this reference file is the same as what was used according to the resources.config provided. Could you confirm or provide the correct reference? 

It seems like the bam files should be changed from 
`@SQ	SN:10	LN:133797422` 
to `@SQ	SN:chr10	LN:133797422` to match the file I have.

**Comment by mroosmalen** [comment]
I have uploaded our reference fasta file to the (demo) link. Can you please try to run it with this reference file?

**Comment by um-pdavila** [comment]
Absolutely.  Will test, provide results and how we generated them from scratch (ie. new PTATO 1.2.1 deployment).

We were able to successfully run the demo dataset after modifying the reference genome fasta files, the shapeit Phasing_reference files and recreating the indexes for both.  I'll provide a detailed script with that as well.  Thank you for your time.

**Comment by shngk** [comment]
@mroosmalen  Thanks for the updated reference file. Could you provide the complementary files necessary to run the demo? Can you confirm that the reference genome, the shapeit phasing reference files, and the corresponding index files would need to be changed as well? Are there any other files that should be changed? 

After modifying the shapeit phasing reference files, the corresponding index files, and the shapeit maps files, I ran it again but still got the "ERROR: No variants to be phased in files" error.

I just want to make sure it's to do with the file formats and not an installation error on our end. Thanks!

**Comment by um-pdavila** [comment]
Hi @shngk,

We successfully ran the demo after using the reference fasta file provided by @mroosmalen.   I'll provided a detailed example here for running the demo on a RHEL/CentOS 7.9 cluster using SLURM.  Just a bit swamped right now.

The only other modifications we made were: 
1. Changing the run.config (set snvs, QC, and cnvs to false) 
2. Removing the "chr" from the shapeit phased VCF files files, we used a bcftools script, provided below.

$ cat PTATO/demo/configs/run.config
...
params {

  run {
    snvs = true
    QC = false
    svs = false
    indels = true
    cnvs = false
  }

The **{ bcftools ...; tabix ...; } &** part of the loop runs both commands in the background, sequentially.  You can also use the parallel command.  I recommend not using awk or sed as there are other issues you have to address then.

$ cat change_chr_notation.sh 
#!/bin/sh
# Source: http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased/
# Sample File CCDG_14151_B01_GRM_WGS_2020-08-05_chr10.filtered.shapeit2-duohmm-phased.vcf.gz
 
# Rename chromosome
# -----------------------------------------------------------------------------
# In VCF header line there also have chromosome notaion, if we use awk/sed to 
# change the notaion, we also have to change it on the VCF header line.
 
# Generate a chromosome renaming file
for CHR in {1..22} X ; do 
    echo chr${CHR} ${CHR}
done >> chr_names.txt
 
# Process files in parallel by sending "bcftools annotate..." command to background : )
for CHR in {1..22} X; do
  { bcftools annotate --rename-chrs chr_names.txt \
           Phasing_reference/CCDG_14151_B01_GRM_WGS_2020-08-05_chr${CHR}.filtered.shapeit2-duohmm-phased.vcf.gz \
    -Oz -o Phasing_reference/CCDG_14151_B01_GRM_WGS_2020-08-05_${CHR}.filtered.shapeit2-duohmm-phased.vcf.gz 
  tabix -p vcf Phasing_reference/CCDG_14151_B01_GRM_WGS_2020-08-05_${CHR}.filtered.shapeit2-duohmm-phased.vcf.gz } &
done
 
{ bcftools annotate --rename-chrs chr_names.txt \
  Phasing_reference/CCDG_14151_B01_GRM_WGS_2020-08-05_chrX.filtered.eagle2-phased.v2.vcf.gz \
    -Oz -o Phasing_reference/CCDG_14151_B01_GRM_WGS_2020-08-05_X.filtered.eagle2-phased.v2.vcf.gz
  tabix -p vcf Phasing_reference/CCDG_14151_B01_GRM_WGS_2020-08-05_X.filtered.eagle2-phased.v2.vcf.gz } &

**Comment by shngk** [comment]
Hi @um-pdavila thank you for your insight, the edited shapeit files helped me successfully pass all of the input to ptato! 

However, I get this new error I'm hoping to resolve: 

```
Error executing process > 'short_variants:indels:get_ptato_vcfs:excludeIndels (excludeIndels demo.chr20_PMCAHH1-WT-C6SC1)'

Caused by:
  Process `short_variants:indels:get_ptato_vcfs:excludeIndels (excludeIndels demo.chr20_PMCAHH1-WT-C6SC1)` terminated with an error exit status (135)

Command executed:

  host=$(hostname)
  echo ${host}
  
  R --slave --file=/gpfs/commons/groups/landau_lab/tprieto/apps/PTATO/scripts/R/excludeIndels.R --args demo.chr20_PMCAHH1-WT-C6SC1.indels.vcf.gz demo.chr20_PMCAHH1-WT-C6SC1.context.sorted.bed PTA_Indel_ExcludeIndellist_normNoGTrenamed.vcf.gz demo.chr20_PMCAHH1-WT-C6SC1.indels.ptato.vcf

Command exit status:
  135

Command output:
  pe2cc3-026.c.nygenome.org

Command error:
  Attaching package: ‘S4Vectors’
  
  The following objects are masked from ‘package:base’:
  
      expand.grid, I, unname
  
  Loading required package: IRanges
  Loading required package: GenomicRanges
  Loading required package: SummarizedExperiment
  Loading required package: Biobase
  Welcome to Bioconductor
  
      Vignettes contain introductory material; view with
      'browseVignettes()'. To cite Bioconductor, see
      'citation("Biobase")', and for packages 'citation("pkgname")'.
  
  
  Attaching package: ‘Biobase’
  
  The following object is masked from ‘package:MatrixGenerics’:
  
      rowMedians
  
  The following objects are masked from ‘package:matrixStats’:
  
      anyMissing, rowMedians
  
  Loading required package: Rsamtools
  Loading required package: Biostrings
  Loading required package: XVector
  
  Attaching package: ‘Biostrings’
  
  The following object is masked from ‘package:base’:
  
      strsplit
  
  
  Attaching package: ‘VariantAnnotation’
  
  The following object is masked from ‘package:base’:
  
      tabulate
  
  Warning messages:
  1: In .bcfHeaderAsSimpleList(header) :
    duplicate keys in header will be forced to unique rownames
  2: In .bcfHeaderAsSimpleList(header) :
    duplicate keys in header will be forced to unique rownames
  .command.sh: line 5: 36229 Bus error               R --slave --file=/gpfs/commons/groups/landau_lab/tprieto/apps/PTATO/scripts/R/excludeIndels.R --args demo.chr20_PMCAHH1-WT-C6SC1.indels.vcf.gz demo.chr20_PMCAHH1-WT-C6SC1.context.sorted.bed PTA_Indel_ExcludeIndellist_normNoGTrenamed.vcf.gz demo.chr20_PMCAHH1-WT-C6SC1.indels.ptato.vcf

Work dir:
  /gpfs/commons/groups/landau_lab/skao/ptato/work/dd/6b50e501835b9b5e429d7cae11dc34

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out
```

I had encountered issues with the VariantAnnotation package before, so I'm wondering if this is a similar issue or possibly another formatting issue.

**Comment by um-pdavila** [comment]
Hi @shngk ,

What version of R are you using, 4.1.2?  How did you install it and the R packages dependancies?  Did you install the "BSgenome.Hsapiens.UCSC.hg38" R package?

Details on how we installed them below.

<pre>
$ spack install r@4.1.2+X+rmath %gcc@8.3.1   # gcc 8.3.1 from Redhat's devtoolset-8

    $ R
      >
          options(Ncpus = 32)    # where 32 < number of cores
          BiocManager::install("BSgenome")
          BiocManager::install("BSgenome.Hsapiens.UCSC.hg38")
          BiocManager::install("copynumber")
          BiocManager::install("cowplot")
</pre>

The ggplot2 package requires the MASS package.  As of 3/22/2023, the current MASS package is 7.3-59, which requires R 4.2, so we will use devtools to install previous version of MASS.

<pre>
    $ R
      >
          BiocManager::install("devtools")
          require(devtools)
          install_version("MASS", version = "7.3-58.3", repos = "http://cran.us.r-project.org")

          BiocManager::install("ggplot2")
          BiocManager::install("gtools")
          BiocManager::install("MutationalPatterns")
          BiocManager::install("randomForest")
          BiocManager::install("scales")
          BiocManager::install("StructuralVariantAnnotation")
          BiocManager::install("VariantAnnotation")
</pre>

**Comment by rhagelaar** [comment]
Since there are no responses, I will close this issue for now

**Comment by domivika** [comment]
Hello,

I have the same problem:

> Trying the chromosomes.txt from the demo data solves that error, now I get this error:
> 
> ```
>   Tue Apr 25 11:17:28 EDT 2023: Running GRIDSS steps: setupreference, preprocess, assemble, call,
>   Tue Apr 25 11:17:28 EDT 2023: Start pre-processing	PMCAHH1-WT-C6_dedup.chr20.bam
>   Tue Apr 25 11:17:28 EDT 2023: Running	CollectGridssMetrics	PMCAHH1-WT-C6_dedup.chr20.bam	first 10000000 records
>   "$timecmd java -Xmx$otherjvmheap $jvm_args -cp $gridss_jar gridss.analysis.CollectGridssMetrics REFERENCE_SEQUENCE=$reference TMP_DIR=$dir ASSUME_SORTED=true I=$f O=$tmp_prefix THRESHOLD_COVERAGE=$maxcoverage FILE_EXTENSION=null GRIDSS_PROGRAM=null GRIDSS_PROGRAM=CollectIdsvMetrics PROGRAM=null PROGRAM=CollectInsertSizeMetrics STOP_AFTER=$metricsrecords $picardoptions" command completed with exit code 1.
> ```
> 
> `ERROR 2023-04-25 15:17:34 ReferenceCommandLineProgram Reference genome used by PMCAHH1-WT-C6_dedup.chr20.bam does not match reference genome /gpfs/commons/groups/landau_lab/tprieto/apps/PTATO/resources/hg38/Homo_sapiens_assembly38.fasta. The reference supplied must match the reference used for every input.`
> 
> However, I think this reference file is the same as what was used according to the resources.config provided. Could you confirm or provide the correct reference?
> 
> It seems like the bam files should be changed from `@SQ SN:10 LN:133797422` to `@SQ SN:chr10 LN:133797422` to match the file I have.

but the reference fasta file has been removed from the demo link. Could you upload it again?

Thanks!
